### ISSUE TITLE
How do I copy the output to the clipboard when I specify -json?

### ISSUE THREAD

**Issue by yasainet** [mufeedvh/code2prompt#24]
Thank you for a very nice application.
I am a beginner in programming, so I especially use "clean-up-code.hbs" and "document-the-code.hbs". Thanks to you, I am enjoying a very comfortable development experience.

Now to the main topic.
When '-json' is specified, json is output to the terminal.
What I am hoping for is that it will also be copied to the clipboard.
If I don't specify -json, I expect the same behaviour as if it were saved to the clipboard as text.

Am I wrong in my thinking? Ideas please.

**Comment by mufeedvh** [comment]
Hey @yasainet, glad to hear that you found this utility useful, thank you! ❤️ 🙌 

The `--json` feature is intended to be used as an API so that you can use the `stdout` from any other application, it only outputs the string and does not copy to the clipboard. I would love to know how you intend to use the feature and why that requires copying the JSON output to the clipboard, if the use case is ideal, I will implement the feature.

**Comment by yasainet** [comment]
Thank you for your response.
I use `code2prompt` every day and can't imagine developing without it!

As for the `json` output, I was mistaken. The basic `code2prompt` command is sufficient to support development.

My apologies. Please close this issue.
